---
title: "Segunda Versión Modelamiento"
author: "Benjamín Zavala"
format: html
editor: visual
---

### Librería

```{r}
pacman::p_load(tidyverse, 
               dplyr, 
               haven, 
               car, 
               magrittr,
               psych,
               readxl, 
               fastDummies,
               stargazer,
               modelsummary,
               summarytools,
               dplyr, lme4, sjPlot, webshot2, htmltools, officer, lmerTest, here, pandoc, fixest)

```

### Bases de datos

```{r}

CIVED_1999 <- readRDS("../output/data_procesada/proc_CIVED_1999.rds")

ICCS_2009 <- readRDS("../output/data_procesada/proc_ICCS_2009.rds")

ICCS_2016 <- readRDS("../output/data_procesada/proc_ICCS_2016.rds")

PACES_2019 <- readRDS("../output/data_procesada/proc_PACES_2019.rds")

```


### CIVED_1999

```{r}

M0 <- lmer(
  voto ~ 1 + (1 | id_colegio),
  data = CIVED_1999,
  REML = TRUE
)

M1 <- lmer(
  voto ~ libro + nivel_educ + Sexo + (1 | id_colegio),
  data = CIVED_1999,
  REML = TRUE
)

M1_a <- lmer(
  voto ~ libro + nivel_educ + Sexo + (1 + libro| id_colegio),
  data = CIVED_1999,
  REML = TRUE
)

M1_b <- lmer(
  voto ~ libro + nivel_educ + Sexo + (1 + nivel_educ | id_colegio),
  data = CIVED_1999,
  REML = TRUE
)

M2 <- lmer(
  voto ~ libro + nivel_educ + Sexo + indice_aula_ind_cwc + aprendizaje_voto_cwc + (1 | id_colegio),
  data = CIVED_1999,
  REML = TRUE
)

M3_a <- lmer(
  voto ~ libro + nivel_educ + Sexo + indice_aula_ind_cwc + aprendizaje_voto_cwc + 
   clima_aula_escuela + (1 | id_colegio),
  data = CIVED_1999,
  REML = TRUE
)

M3_b <- lmer(
  voto ~ libro + nivel_educ + Sexo + indice_aula_ind_cwc + aprendizaje_voto_cwc +    perp_aprendizaje_voto_esc + (1 | id_colegio),
  data = CIVED_1999,
  REML = TRUE
)


M4_a1 <- lmer(
  voto ~ libro * clima_aula_escuela +
    nivel_educ + Sexo + indice_aula_ind_cwc + aprendizaje_voto_cwc + (1 + libro | id_colegio),
  data = CIVED_1999,
  REML = TRUE
)

M4_b1 <- lmer(
  voto ~ nivel_educ * clima_aula_escuela +
    libro + Sexo + indice_aula_ind_cwc + aprendizaje_voto_cwc + (1 + nivel_educ | id_colegio),
  data = CIVED_1999,
  REML = TRUE
)

M4_a2 <- lmer(
  voto ~ libro * perp_aprendizaje_voto_esc + 
    libro + Sexo + indice_aula_ind_cwc + aprendizaje_voto_cwc + (1 + libro | id_colegio),
  data = CIVED_1999,
  REML = TRUE
)

M4_b2 <- lmer(
  voto ~ nivel_educ * perp_aprendizaje_voto_esc +
    libro + Sexo + indice_aula_ind_cwc + aprendizaje_voto_cwc + (1 + nivel_educ| id_colegio),
  data = CIVED_1999,
  REML = TRUE
)

```

### ICCS 2009

```{r}

M0 <- lmer(
  voto ~ 1 +(1 | id_colegio),
  data = ICCS_2009,
  REML = TRUE
)

M1 <- lmer(
  voto ~ libro + nivel_educ + Sexo + (1 | id_colegio),
  data = ICCS_2009,
  REML = TRUE
)

M1_a <- lmer(
  voto ~ libro + nivel_educ + Sexo + (1 + libro| id_colegio),
  data = ICCS_2009,
  REML = TRUE
)

M1_b <- lmer(
  voto ~ libro + nivel_educ + Sexo + (1 + nivel_educ | id_colegio),
  data = ICCS_2009,
  REML = TRUE
)

M2 <- lmer(
  voto ~ libro + nivel_educ + Sexo + participacion_voto_cwc + asamblea_cwc + indice_aula_ind_cwc + (1 | id_colegio),
  data = ICCS_2009,
  REML = TRUE
)

M3_a <- lmer(
  voto ~ libro + nivel_educ + Sexo +  participacion_voto_cwc + asamblea_cwc + indice_aula_ind_cwc + clima_aula_escuela (1 | id_colegio),
  data = ICCS_2009,
  REML = TRUE
)

M3_b <- lmer(
  voto ~ libro + nivel_educ + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + tasa_voto_escuela + (1 | id_colegio),
  data = ICCS_2009,
  REML = TRUE
)

M3_c <- lmer(
  voto ~ libro + nivel_educ + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + tasa_asamblea_escuela + (1 | id_colegio),
  data = ICCS_2009,
  REML = TRUE
)

M4_a1 <- lmer(
  voto ~ libro * clima_aula_escuela +
    nivel_educ + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + (1 + libro | id_colegio),
  data = ICCS_2009,
  REML = TRUE
)

M4_b1 <- lmer(
  voto ~ nivel_educ * clima_aula_escuela +
    libro + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + (1 + nivel_educ | id_colegio),
  data = ICCS_2009,
  REML = TRUE
)

M4_a2 <- lmer(
  voto ~ libro * tasa_voto_escuela + 
    libro + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + (1 + libro | id_colegio),
  data = ICCS_2009,
  REML = TRUE
)

M4_b2 <- lmer(
  voto ~ nivel_educ * tasa_voto_escuela +
    libro + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + (1 + nivel_educ| id_colegio),
  data = ICCS_2009,
  REML = TRUE
)

M4_c1 <- lmer(
  voto ~ libro * tasa_asamblea_escuela +
    nivel_educ  + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + (1 + libro| id_colegio),
  data = ICCS_2009,
  REML = TRUE
)


M4_c2 <- lmer(
  voto ~ nivel_educ * tasa_asamblea_escuela +
    libro + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + (1 + nivel_educ| id_colegio),
  data = ICCS_2009,
  REML = TRUE
)

```

### ICCS 2016

```{r}

M0 <- lmer(
  voto ~ 1 +(1 | id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

M1 <- lmer(
  voto ~ libro + nivel_educ + Sexo + (1 | id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

M1_a <- lmer(
  voto ~ libro + nivel_educ + Sexo + (1 + libro| id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

M1_b <- lmer(
  voto ~ libro + nivel_educ + Sexo + (1 + nivel_educ | id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

M2 <- lmer(
  voto ~ libro + nivel_educ + Sexo + participacion_voto_cwc + asamblea_cwc + indice_aula_ind_cwc + aprendizaje_voto_cwc + (1 | id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

M3_a <- lmer(
  voto ~ libro + nivel_educ + Sexo +  participacion_voto_cwc + asamblea_cwc + indice_aula_ind_cwc + clima_aula_escuela + aprendizaje_voto_cwc + (1 | id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

M3_b <- lmer(
  voto ~ libro + nivel_educ + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + tasa_voto_escuela + aprendizaje_voto_cwc + (1 | id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

M3_c <- lmer(
  voto ~ libro + nivel_educ + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + tasa_asamblea_escuela + aprendizaje_voto_cwc + (1 | id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

M3_d <- lmer(
  voto ~ libro + nivel_educ + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc +	perp_aprendizaje_voto_esc + aprendizaje_voto_cwc + (1 | id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

M4_a1 <- lmer(
  voto ~ libro * clima_aula_escuela +
    nivel_educ + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + aprendizaje_voto_cwc + (1 + libro | id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

M4_b1 <- lmer(
  voto ~ nivel_educ * clima_aula_escuela +
    libro + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + aprendizaje_voto_cwc + (1 + nivel_educ | id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

M4_a2 <- lmer(
  voto ~ libro * tasa_voto_escuela + 
    libro + Sexo + indice_aula_ind + participacion_voto_cwc + asamblea_cwc + aprendizaje_voto_cwc + (1 + libro | id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

M4_b2 <- lmer(
  voto ~ nivel_educ * tasa_voto_escuela +
    libro + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + aprendizaje_voto_cwc + (1 + nivel_educ| id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

M4_c1 <- lmer(
  voto ~ libro * tasa_asamblea_escuela +
    nivel_educ  + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + aprendizaje_voto_cwc + (1 + libro| id_colegio),
  data = ICCS_2016,
  REML = TRUE
)


M4_c2 <- lmer(
  voto ~ nivel_educ * tasa_asamblea_escuela +
    libro + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + aprendizaje_voto_cwc + (1 + nivel_educ| id_colegio),
  data = ICCS_2016,
  REML = TRUE
)


M4_d1 <- lmer(
  voto ~ libro * perp_aprendizaje_voto_esc +
    nivel_educ  + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + aprendizaje_voto_cwc + (1 + libro| id_colegio),
  data = ICCS_2016,
  REML = TRUE
)


M4_d2 <- lmer(
  voto ~ nivel_educ * perp_aprendizaje_voto_esc +
    libro + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + aprendizaje_voto_cwc + (1 + nivel_educ| id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

```

#### PACES 2019

```{r}
M0 <- lmer(
  voto ~ 1 +(1 | id_colegio),
  data = PACES_2019,
  REML = TRUE
)

M1 <- lmer(
  voto ~ libro + nivel_educ + Sexo + (1 | id_colegio),
  data = PACES_2019,
  REML = TRUE
)

M1_a <- lmer(
  voto ~ libro + nivel_educ + Sexo + (1 + libro| id_colegio),
  data = PACES_2019,
  REML = TRUE
)

M1_b <- lmer(
  voto ~ libro + nivel_educ + Sexo + (1 + nivel_educ | id_colegio),
  data = PACES_2019,
  REML = TRUE
)

M2 <- lmer(
  voto ~ libro + nivel_educ + Sexo + participacion_voto_cwc + asamblea_cwc + indice_aula_ind_cwc + (1 | id_colegio),
  data = PACES_2019,
  REML = TRUE
)

M3_a <- lmer(
  voto ~ libro + nivel_educ + Sexo +  participacion_voto_cwc + asamblea_cwc + indice_aula_ind_cwc + clima_aula_escuela (1 | id_colegio),
  data = PACES_2019,
  REML = TRUE
)

M3_b <- lmer(
  voto ~ libro + nivel_educ + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + tasa_voto_escuela + (1 | id_colegio),
  data = PACES_2019,
  REML = TRUE
)

M3_c <- lmer(
  voto ~ libro + nivel_educ + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + tasa_asamblea_escuela + (1 | id_colegio),
  data = PACES_2019,
  REML = TRUE
)

M4_a1 <- lmer(
  voto ~ libro * clima_aula_escuela +
    nivel_educ + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + (1 + libro | id_colegio),
  data = PACES_2019,
  REML = TRUE
)

M4_b1 <- lmer(
  voto ~ nivel_educ * clima_aula_escuela +
    libro + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + (1 + nivel_educ | id_colegio),
  data = PACES_2019,
  REML = TRUE
)

M4_a2 <- lmer(
  voto ~ libro * tasa_voto_escuela + 
    libro + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + (1 + libro | id_colegio),
  data = PACES_2019,
  REML = TRUE
)

M4_b2 <- lmer(
  voto ~ nivel_educ * tasa_voto_escuela +
    libro + Sexo + indice_aula_ind + participacion_voto + asamblea + (1 + nivel_educ| id_colegio),
  data = PACES_2019,
  REML = TRUE
)

M4_c1 <- lmer(
  voto ~ libro * tasa_asamblea_escuela +
    nivel_educ  + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + (1 + libro| id_colegio),
  data = PACES_2019,
  REML = TRUE
)


M4_c2 <- lmer(
  voto ~ nivel_educ * tasa_asamblea_escuela +
    libro + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + (1 + nivel_educ| id_colegio),
  data = PACES_2019,
  REML = TRUE
)

```

## Tablas exportables

```{r}

etiquetas <- c(
  "M0: Vacío",
  "M1: Nivel 1",
  "M1_a: Pend. aleat. (libro)",
  "M1_b: Pend. aleat. (nivel_educ)",
  "M2: + Controles N1",
  "M3_a: + Clima de aula (escuela)",
  "M3_b: + Percepción aprendizaje (escuela)",
  "M4_a1: Libro × Clima aula",
  "M4_b1: Nivel educ × Clima aula",
  "M4_a2: Libro × Percepción aprendizaje",
  "M4_b2: Nivel educ × Percepción aprendizaje"
)

archivo_docx <- here::here("output", "Modelos_2", "CIVED_1999", "modelos_CIVED_1999_voto.doc")

tab_model(
  M0, M1, M1_a, M1_b, M2, M3_a, M3_b, M4_a1, M4_b1, M4_a2, M4_b2,
  show.re.var = TRUE,
  show.icc    = TRUE,
  show.r2     = TRUE,
  show.ci     = FALSE,
  show.p      = FALSE,
  p.style     = "stars",
  dv.labels   = etiquetas,
  file        = archivo_docx
)

```

### 







