---
title: "Modelamiento_indice"
format: html
editor: visual
---

### Librería

```{r}
pacman::p_load(tidyverse, 
               dplyr, 
               haven, 
               car, 
               magrittr,
               psych,
               readxl, 
               fastDummies,
               stargazer,
               modelsummary,
               summarytools,
               dplyr, lme4, sjPlot, webshot2, htmltools, officer, lmerTest, here, pandoc, fixest)

```

### Bases de datos

```{r}

CIVED_1999 <- readRDS("../output/data_procesada/proc_CIVED_1999.rds")

ICCS_2009 <- readRDS("../output/data_procesada/proc_ICCS_2009.rds")

ICCS_2016 <- readRDS("../output/data_procesada/proc_ICCS_2016.rds")

PACES_2019 <- readRDS("../output/data_procesada/proc_PACES_2019.rds")


```


#### Función ANOVA

```{r}
comparar_pendiente_aleatoria <- function(modelo_fijo, modelo_aleatorio, nombre_cohorte, nombre_variable) {
  comp <- anova(modelo_fijo, modelo_aleatorio)
  data.frame(
    Cohorte      = nombre_cohorte,
    Pendiente    = nombre_variable,
    AIC_fijo     = round(comp$AIC[1], 1),
    AIC_aleat    = round(comp$AIC[2], 1),
    BIC_fijo     = round(comp$BIC[1], 1),
    BIC_aleat    = round(comp$BIC[2], 1),
    logLik_fijo  = round(comp$logLik[1], 1),
    logLik_aleat = round(comp$logLik[2], 1),
    Chisq        = round(comp$Chisq[2], 2),
    Df           = comp$Df[2],
    p_valor      = signif(comp[["Pr(>Chisq)"]][2], 3)
  )
}
```

### CIVED_1999

```{r}


M0 <- lmer(
  indice_voto_std ~ 1 + (1 | id_colegio),
  data = CIVED_1999,
  REML = TRUE
)

M1 <- lmer(
  indice_voto_std ~ libro + nivel_educ + Sexo + (1 | id_colegio),
  data = CIVED_1999,
  REML = TRUE
)

M1_a <- lmer(
  indice_voto_std ~ libro + nivel_educ + Sexo + (1 + libro| id_colegio),
  data = CIVED_1999,
  REML = TRUE
)

M1_b <- lmer(
  indice_voto_std ~ libro + nivel_educ + Sexo + (1 + nivel_educ | id_colegio),
  data = CIVED_1999,
  REML = TRUE
)

M2 <- lmer(
  indice_voto_std ~ libro + nivel_educ + Sexo + indice_aula_ind_cwc + aprendizaje_voto_cwc + (1 | id_colegio),
  data = CIVED_1999,
  REML = TRUE
)

M3_a <- lmer(
  indice_voto_std ~ libro + nivel_educ + Sexo + indice_aula_ind_cwc + aprendizaje_voto_cwc + 
   clima_aula_escuela + (1 | id_colegio),
  data = CIVED_1999,
  REML = TRUE
)

M3_b <- lmer(
  indice_voto_std ~ libro + nivel_educ + Sexo + indice_aula_ind_cwc + aprendizaje_voto_cwc + perp_aprendizaje_voto_esc + (1 | id_colegio),
  data = CIVED_1999,
  REML = TRUE
)

# --- Interacciones con contextuales de escuela ---

M4_a1 <- lmer(
  indice_voto_std ~ libro * clima_aula_escuela +
    nivel_educ + Sexo + indice_aula_ind_cwc + aprendizaje_voto_cwc + (1 + libro | id_colegio),
  data = CIVED_1999,
  REML = TRUE
)

M4_b1 <- lmer(
  indice_voto_std ~ nivel_educ * clima_aula_escuela +
    libro + Sexo + indice_aula_ind_cwc + aprendizaje_voto_cwc + (1 + nivel_educ | id_colegio),
  data = CIVED_1999,
  REML = TRUE
)

M4_a2 <- lmer(
  indice_voto_std ~ libro * perp_aprendizaje_voto_esc + 
    nivel_educ + Sexo + indice_aula_ind_cwc + aprendizaje_voto_cwc + (1 + libro | id_colegio),
  data = CIVED_1999,
  REML = TRUE
)

M4_b2 <- lmer(
  indice_voto_std ~ nivel_educ * perp_aprendizaje_voto_esc +
    libro + Sexo + indice_aula_ind_cwc + aprendizaje_voto_cwc + (1 + nivel_educ| id_colegio),
  data = CIVED_1999,
  REML = TRUE
)

# --- Interacciones con variables centradas (individuales, cwc) ---

M4_c1 <- lmer(
  indice_voto_std ~ libro * indice_aula_ind_cwc +
    nivel_educ + Sexo + aprendizaje_voto_cwc + (1 + libro | id_colegio),
  data = CIVED_1999,
  REML = TRUE
)

M4_c2 <- lmer(
  indice_voto_std ~ nivel_educ * indice_aula_ind_cwc +
    libro + Sexo + aprendizaje_voto_cwc + (1 + nivel_educ | id_colegio),
  data = CIVED_1999,
  REML = TRUE
)

M4_d1 <- lmer(
  indice_voto_std ~ libro * aprendizaje_voto_cwc +
    nivel_educ + Sexo + indice_aula_ind_cwc + (1 + libro | id_colegio),
  data = CIVED_1999,
  REML = TRUE
)

M4_d2 <- lmer(
  indice_voto_std ~ nivel_educ * aprendizaje_voto_cwc +
    libro + Sexo + indice_aula_ind_cwc + (1 + nivel_educ | id_colegio),
  data = CIVED_1999,
  REML = TRUE
)

```

#### Tabla modelos

```{r}


etiquetas <- c(
  "M0: Vacío",
  "M1: Nivel 1",
  "M1_a: Pend. aleat. (libro)",
  "M1_b: Pend. aleat. (nivel_educ)",
  "M2: + Controles N1",
  "M3_a: + Clima de aula (escuela)",
  "M3_b: + Percepción aprendizaje (escuela)",
  "M4_a1: Libro × Clima aula",
  "M4_b1: Nivel educ × Clima aula",
  "M4_a2: Libro × Percepción aprendizaje",
  "M4_b2: Nivel educ × Percepción aprendizaje",
  "M4_c1: Libro × Clima aula (ind)",
  "M4_c2: Nivel educ × Clima aula (ind)",
  "M4_d1: Libro × Aprendizaje voto (ind)",
  "M4_d2: Nivel educ × Aprendizaje voto (ind)"
)

archivo_docx <- here::here("output", "Modelos_indice", "modelos_CIVED_1999_indice_voto.doc")

tab_model(
  M0, M1, M1_a, M1_b, M2, M3_a, M3_b,
  M4_a1, M4_b1, M4_a2, M4_b2, M4_c1, M4_c2, M4_d1, M4_d2,
  show.re.var = TRUE,
  show.icc    = TRUE,
  show.r2     = TRUE,
  show.ci     = FALSE,
  show.p      = FALSE,
  p.style     = "stars",
  dv.labels   = etiquetas,
  file        = archivo_docx
)

```

#### Test ANOVA

```{r}
anova_CIVED_1999 <- dplyr::bind_rows(
  comparar_pendiente_aleatoria(M1, M1_a, "CIVED_1999", "libro"),
  comparar_pendiente_aleatoria(M1, M1_b, "CIVED_1999", "nivel_educ")
)
```


### ICCS 2009

```{r}


M0 <- lmer(
  indice_voto_std ~ 1 +(1 | id_colegio),
  data = ICCS_2009,
  REML = TRUE
)

M1 <- lmer(
  indice_voto_std ~ libro + nivel_educ + Sexo + (1 | id_colegio),
  data = ICCS_2009,
  REML = TRUE
)

M1_a <- lmer(
  indice_voto_std ~ libro + nivel_educ + Sexo + (1 + libro| id_colegio),
  data = ICCS_2009,
  REML = TRUE
)

M1_b <- lmer(
  indice_voto_std ~ libro + nivel_educ + Sexo + (1 + nivel_educ | id_colegio),
  data = ICCS_2009,
  REML = TRUE
)

M2 <- lmer(
  indice_voto_std ~ libro + nivel_educ + Sexo + participacion_voto_cwc + asamblea_cwc + indice_aula_ind_cwc + (1 | id_colegio),
  data = ICCS_2009,
  REML = TRUE
)

M3_a <- lmer(
  indice_voto_std ~ libro + nivel_educ + Sexo +  participacion_voto_cwc + asamblea_cwc + indice_aula_ind_cwc + clima_aula_escuela + (1 | id_colegio),
  data = ICCS_2009,
  REML = TRUE
)

M3_b <- lmer(
  indice_voto_std ~ libro + nivel_educ + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + tasa_voto_escuela + (1 | id_colegio),
  data = ICCS_2009,
  REML = TRUE
)

M3_c <- lmer(
  indice_voto_std ~ libro + nivel_educ + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + tasa_asamblea_escuela + (1 | id_colegio),
  data = ICCS_2009,
  REML = TRUE
)

# --- Interacciones con contextuales de escuela ---

M4_a1 <- lmer(
  indice_voto_std ~ libro * clima_aula_escuela +
    nivel_educ + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + (1 + libro | id_colegio),
  data = ICCS_2009,
  REML = TRUE
)

M4_b1 <- lmer(
  indice_voto_std ~ nivel_educ * clima_aula_escuela +
    libro + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + (1 + nivel_educ | id_colegio),
  data = ICCS_2009,
  REML = TRUE
)

M4_a2 <- lmer(
  indice_voto_std ~ libro * tasa_voto_escuela + 
    nivel_educ + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + (1 + libro | id_colegio),
  data = ICCS_2009,
  REML = TRUE
)

M4_b2 <- lmer(
  indice_voto_std ~ nivel_educ * tasa_voto_escuela +
    libro + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + (1 + nivel_educ| id_colegio),
  data = ICCS_2009,
  REML = TRUE
)

M4_c1 <- lmer(
  indice_voto_std ~ libro * tasa_asamblea_escuela +
    nivel_educ  + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + (1 + libro| id_colegio),
  data = ICCS_2009,
  REML = TRUE
)

M4_c2 <- lmer(
  indice_voto_std ~ nivel_educ * tasa_asamblea_escuela +
    libro + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + (1 + nivel_educ| id_colegio),
  data = ICCS_2009,
  REML = TRUE
)

# --- Interacciones con variables centradas (individuales, cwc) ---

M4_d1 <- lmer(
  indice_voto_std ~ libro * indice_aula_ind_cwc +
    nivel_educ + Sexo + participacion_voto_cwc + asamblea_cwc + (1 + libro | id_colegio),
  data = ICCS_2009,
  REML = TRUE
)

M4_d2 <- lmer(
  indice_voto_std ~ nivel_educ * indice_aula_ind_cwc +
    libro + Sexo + participacion_voto_cwc + asamblea_cwc + (1 + nivel_educ | id_colegio),
  data = ICCS_2009,
  REML = TRUE
)

M4_e1 <- lmer(
  indice_voto_std ~ libro * participacion_voto_cwc +
    nivel_educ + Sexo + indice_aula_ind_cwc + asamblea_cwc + (1 + libro | id_colegio),
  data = ICCS_2009,
  REML = TRUE
)

M4_e2 <- lmer(
  indice_voto_std ~ nivel_educ * participacion_voto_cwc +
    libro + Sexo + indice_aula_ind_cwc + asamblea_cwc + (1 + nivel_educ | id_colegio),
  data = ICCS_2009,
  REML = TRUE
)

M4_f1 <- lmer(
  indice_voto_std ~ libro * asamblea_cwc +
    nivel_educ + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + (1 + libro | id_colegio),
  data = ICCS_2009,
  REML = TRUE
)

M4_f2 <- lmer(
  indice_voto_std ~ nivel_educ * asamblea_cwc +
    libro + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + (1 + nivel_educ | id_colegio),
  data = ICCS_2009,
  REML = TRUE
)

```

#### Tabla Modelos 

```{r}
etiquetas <- c(
  "M0: Vacío",
  "M1: Nivel 1",
  "M1_a: Pend. aleat. (libro)",
  "M1_b: Pend. aleat. (nivel_educ)",
  "M2: + Controles N1 (CWC)",
  "M3_a: + Clima de aula (escuela)",
  "M3_b: + Tasa de votación (escuela)",
  "M3_c: + Tasa de asamblea (escuela)",
  "M4_a1: Libro × Clima aula",
  "M4_b1: Nivel educ × Clima aula",
  "M4_a2: Libro × Tasa votación",
  "M4_b2: Nivel educ × Tasa votación",
  "M4_c1: Libro × Tasa asamblea",
  "M4_c2: Nivel educ × Tasa asamblea",
  "M4_d1: Libro × Clima aula (ind)",
  "M4_d2: Nivel educ × Clima aula (ind)",
  "M4_e1: Libro × Participación voto (ind)",
  "M4_e2: Nivel educ × Participación voto (ind)",
  "M4_f1: Libro × Asamblea (ind)",
  "M4_f2: Nivel educ × Asamblea (ind)"
)

archivo_docx <- here::here("output", "Modelos_indice", "modelos_ICCS_2009_indice_voto.doc")

tab_model(
  M0, M1, M1_a, M1_b, M2, M3_a, M3_b, M3_c,
  M4_a1, M4_b1, M4_a2, M4_b2, M4_c1, M4_c2,
  M4_d1, M4_d2, M4_e1, M4_e2, M4_f1, M4_f2,
  show.re.var = TRUE,
  show.icc    = TRUE,
  show.r2     = TRUE,
  show.ci     = FALSE,
  show.p      = FALSE,
  p.style     = "stars",
  dv.labels   = etiquetas,
  file        = archivo_docx
)
```

#### Test ANOVA

```{r}
anova_ICCS_2009 <- dplyr::bind_rows(
  comparar_pendiente_aleatoria(M1, M1_a, "ICCS_2009", "libro"),
  comparar_pendiente_aleatoria(M1, M1_b, "ICCS_2009", "nivel_educ")
)
```


### ICCS 2016

```{r}


M0 <- lmer(
  indice_voto_std ~ 1 +(1 | id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

M1 <- lmer(
  indice_voto_std ~ libro + nivel_educ + Sexo + (1 | id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

M1_a <- lmer(
  indice_voto_std ~ libro + nivel_educ + Sexo + (1 + libro| id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

M1_b <- lmer(
  indice_voto_std ~ libro + nivel_educ + Sexo + (1 + nivel_educ | id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

M2 <- lmer(
  indice_voto_std ~ libro + nivel_educ + Sexo + participacion_voto_cwc + asamblea_cwc + indice_aula_ind_cwc + aprendizaje_voto_cwc + (1 | id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

M3_a <- lmer(
  indice_voto_std ~ libro + nivel_educ + Sexo +  participacion_voto_cwc + asamblea_cwc + indice_aula_ind_cwc + clima_aula_escuela + aprendizaje_voto_cwc + (1 | id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

M3_b <- lmer(
  indice_voto_std ~ libro + nivel_educ + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + tasa_voto_escuela + aprendizaje_voto_cwc + (1 | id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

M3_c <- lmer(
  indice_voto_std ~ libro + nivel_educ + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + tasa_asamblea_escuela + aprendizaje_voto_cwc + (1 | id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

M3_d <- lmer(
  indice_voto_std ~ libro + nivel_educ + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc +	perp_aprendizaje_voto_esc + aprendizaje_voto_cwc + (1 | id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

# --- Interacciones con contextuales de escuela ---

M4_a1 <- lmer(
  indice_voto_std ~ libro * clima_aula_escuela +
    nivel_educ + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + aprendizaje_voto_cwc + (1 + libro | id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

M4_b1 <- lmer(
  indice_voto_std ~ nivel_educ * clima_aula_escuela +
    libro + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + aprendizaje_voto_cwc + (1 + nivel_educ | id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

M4_a2 <- lmer(
  indice_voto_std ~ libro * tasa_voto_escuela + 
    nivel_educ + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + aprendizaje_voto_cwc + (1 + libro | id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

M4_b2 <- lmer(
  indice_voto_std ~ nivel_educ * tasa_voto_escuela +
    libro + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + aprendizaje_voto_cwc + (1 + nivel_educ| id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

M4_c1 <- lmer(
  indice_voto_std ~ libro * tasa_asamblea_escuela +
    nivel_educ  + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + aprendizaje_voto_cwc + (1 + libro| id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

M4_c2 <- lmer(
  indice_voto_std ~ nivel_educ * tasa_asamblea_escuela +
    libro + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + aprendizaje_voto_cwc + (1 + nivel_educ| id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

M4_d1 <- lmer(
  indice_voto_std ~ libro * perp_aprendizaje_voto_esc +
    nivel_educ  + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + aprendizaje_voto_cwc + (1 + libro| id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

M4_d2 <- lmer(
  indice_voto_std ~ nivel_educ * perp_aprendizaje_voto_esc +
    libro + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + aprendizaje_voto_cwc + (1 + nivel_educ| id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

# --- Interacciones con variables centradas (individuales, cwc) ---

M4_e1 <- lmer(
  indice_voto_std ~ libro * indice_aula_ind_cwc +
    nivel_educ + Sexo + participacion_voto_cwc + asamblea_cwc + aprendizaje_voto_cwc + (1 + libro | id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

M4_e2 <- lmer(
  indice_voto_std ~ nivel_educ * indice_aula_ind_cwc +
    libro + Sexo + participacion_voto_cwc + asamblea_cwc + aprendizaje_voto_cwc + (1 + nivel_educ | id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

M4_f1 <- lmer(
  indice_voto_std ~ libro * participacion_voto_cwc +
    nivel_educ + Sexo + indice_aula_ind_cwc + asamblea_cwc + aprendizaje_voto_cwc + (1 + libro | id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

M4_f2 <- lmer(
  indice_voto_std ~ nivel_educ * participacion_voto_cwc +
    libro + Sexo + indice_aula_ind_cwc + asamblea_cwc + aprendizaje_voto_cwc + (1 + nivel_educ | id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

M4_g1 <- lmer(
  indice_voto_std ~ libro * asamblea_cwc +
    nivel_educ + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + aprendizaje_voto_cwc + (1 + libro | id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

M4_g2 <- lmer(
  indice_voto_std ~ nivel_educ * asamblea_cwc +
    libro + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + aprendizaje_voto_cwc + (1 + nivel_educ | id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

M4_h1 <- lmer(
  indice_voto_std ~ libro * aprendizaje_voto_cwc +
    nivel_educ + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + (1 + libro | id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

M4_h2 <- lmer(
  indice_voto_std ~ nivel_educ * aprendizaje_voto_cwc +
    libro + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + (1 + nivel_educ | id_colegio),
  data = ICCS_2016,
  REML = TRUE
)

```

#### Tabla Modelos

```{r}
etiquetas <- c(
  "M0: Vacío",
  "M1: Nivel 1",
  "M1_a: Pend. aleat. (libro)",
  "M1_b: Pend. aleat. (nivel_educ)",
  "M2: + Controles N1 (CWC)",
  "M3_a: + Clima de aula (escuela)",
  "M3_b: + Tasa de votación (escuela)",
  "M3_c: + Tasa de asamblea (escuela)",
  "M3_d: + Percepción aprendizaje (escuela)",
  "M4_a1: Libro × Clima aula",
  "M4_b1: Nivel educ × Clima aula",
  "M4_a2: Libro × Tasa votación",
  "M4_b2: Nivel educ × Tasa votación",
  "M4_c1: Libro × Tasa asamblea",
  "M4_c2: Nivel educ × Tasa asamblea",
  "M4_d1: Libro × Percepción aprendizaje",
  "M4_d2: Nivel educ × Percepción aprendizaje",
  "M4_e1: Libro × Clima aula (ind)",
  "M4_e2: Nivel educ × Clima aula (ind)",
  "M4_f1: Libro × Participación voto (ind)",
  "M4_f2: Nivel educ × Participación voto (ind)",
  "M4_g1: Libro × Asamblea (ind)",
  "M4_g2: Nivel educ × Asamblea (ind)",
  "M4_h1: Libro × Aprendizaje voto (ind)",
  "M4_h2: Nivel educ × Aprendizaje voto (ind)"
)

archivo_docx <- here::here("output", "Modelos_indice", "modelos_ICCS_2016_indice_voto.doc")

tab_model(
  M0, M1, M1_a, M1_b, M2, M3_a, M3_b, M3_c, M3_d,
  M4_a1, M4_b1, M4_a2, M4_b2, M4_c1, M4_c2, M4_d1, M4_d2,
  M4_e1, M4_e2, M4_f1, M4_f2, M4_g1, M4_g2, M4_h1, M4_h2,
  show.re.var = TRUE,
  show.icc    = TRUE,
  show.r2     = TRUE,
  show.ci     = FALSE,
  show.p      = FALSE,
  p.style     = "stars",
  dv.labels   = etiquetas,
  file        = archivo_docx
)
```

#### Test ANOVA

```{r}
anova_ICCS_2016 <- dplyr::bind_rows(
  comparar_pendiente_aleatoria(M1, M1_a, "ICCS_2016", "libro"),
  comparar_pendiente_aleatoria(M1, M1_b, "ICCS_2016", "nivel_educ")
)

```

### PACES 2019

```{r}
M0 <- lmer(
  indice_voto_std ~ 1 +(1 | id_colegio),
  data = PACES_2019,
  REML = TRUE
)

M1 <- lmer(
  indice_voto_std ~ libro + nivel_educ + Sexo + (1 | id_colegio),
  data = PACES_2019,
  REML = TRUE
)

M1_a <- lmer(
  indice_voto_std ~ libro + nivel_educ + Sexo + (1 + libro| id_colegio),
  data = PACES_2019,
  REML = TRUE
)

M1_b <- lmer(
  indice_voto_std ~ libro + nivel_educ + Sexo + (1 + nivel_educ | id_colegio),
  data = PACES_2019,
  REML = TRUE
)

M2 <- lmer(
  indice_voto_std ~ libro + nivel_educ + Sexo + participacion_voto_cwc + asamblea_cwc + indice_aula_ind_cwc + (1 | id_colegio),
  data = PACES_2019,
  REML = TRUE
)

M3_a <- lmer(
  indice_voto_std ~ libro + nivel_educ + Sexo +  participacion_voto_cwc + asamblea_cwc + indice_aula_ind_cwc + clima_aula_escuela + (1 | id_colegio),
  data = PACES_2019,
  REML = TRUE
)

M3_b <- lmer(
  indice_voto_std ~ libro + nivel_educ + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + tasa_voto_escuela + (1 | id_colegio),
  data = PACES_2019,
  REML = TRUE
)

M3_c <- lmer(
  indice_voto_std ~ libro + nivel_educ + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + tasa_asamblea_escuela + (1 | id_colegio),
  data = PACES_2019,
  REML = TRUE
)

# --- Interacciones con contextuales de escuela ---

M4_a1 <- lmer(
  indice_voto_std ~ libro * clima_aula_escuela +
    nivel_educ + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + (1 + libro | id_colegio),
  data = PACES_2019,
  REML = TRUE
)

M4_b1 <- lmer(
  indice_voto_std ~ nivel_educ * clima_aula_escuela +
    libro + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + (1 + nivel_educ | id_colegio),
  data = PACES_2019,
  REML = TRUE
)

M4_a2 <- lmer(
  indice_voto_std ~ libro * tasa_voto_escuela + 
    nivel_educ + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + (1 + libro | id_colegio),
  data = PACES_2019,
  REML = TRUE
)

M4_b2 <- lmer(
  indice_voto_std ~ nivel_educ * tasa_voto_escuela +
    libro + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + (1 + nivel_educ| id_colegio),
  data = PACES_2019,
  REML = TRUE
)

M4_c1 <- lmer(
  indice_voto_std ~ libro * tasa_asamblea_escuela +
    nivel_educ  + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + (1 + libro| id_colegio),
  data = PACES_2019,
  REML = TRUE
)

M4_c2 <- lmer(
  indice_voto_std ~ nivel_educ * tasa_asamblea_escuela +
    libro + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + asamblea_cwc + (1 + nivel_educ| id_colegio),
  data = PACES_2019,
  REML = TRUE
)

# --- Interacciones con variables centradas (individuales, cwc) ---

M4_d1 <- lmer(
  indice_voto_std ~ libro * indice_aula_ind_cwc +
    nivel_educ + Sexo + participacion_voto_cwc + asamblea_cwc + (1 + libro | id_colegio),
  data = PACES_2019,
  REML = TRUE
)

M4_d2 <- lmer(
  indice_voto_std ~ nivel_educ * indice_aula_ind_cwc +
    libro + Sexo + participacion_voto_cwc + asamblea_cwc + (1 + nivel_educ | id_colegio),
  data = PACES_2019,
  REML = TRUE
)

M4_e1 <- lmer(
  indice_voto_std ~ libro * participacion_voto_cwc +
    nivel_educ + Sexo + indice_aula_ind_cwc + asamblea_cwc + (1 + libro | id_colegio),
  data = PACES_2019,
  REML = TRUE
)

M4_e2 <- lmer(
  indice_voto_std ~ nivel_educ * participacion_voto_cwc +
    libro + Sexo + indice_aula_ind_cwc + asamblea_cwc + (1 + nivel_educ | id_colegio),
  data = PACES_2019,
  REML = TRUE
)

M4_f1 <- lmer(
  indice_voto_std ~ libro * asamblea_cwc +
    nivel_educ + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + (1 + libro | id_colegio),
  data = PACES_2019,
  REML = TRUE
)

M4_f2 <- lmer(
  indice_voto_std ~ nivel_educ * asamblea_cwc +
    libro + Sexo + indice_aula_ind_cwc + participacion_voto_cwc + (1 + nivel_educ | id_colegio),
  data = PACES_2019,
  REML = TRUE
)

```


#### Tabla Modelos

```{r}
etiquetas <- c(
  "M0: Vacío",
  "M1: Nivel 1",
  "M1_a: Pend. aleat. (libro)",
  "M1_b: Pend. aleat. (nivel_educ)",
  "M2: + Controles N1 (CWC)",
  "M3_a: + Clima de aula (escuela)",
  "M3_b: + Tasa de votación (escuela)",
  "M3_c: + Tasa de asamblea (escuela)",
  "M4_a1: Libro × Clima aula",
  "M4_b1: Nivel educ × Clima aula",
  "M4_a2: Libro × Tasa votación",
  "M4_b2: Nivel educ × Tasa votación",
  "M4_c1: Libro × Tasa asamblea",
  "M4_c2: Nivel educ × Tasa asamblea",
  "M4_d1: Libro × Clima aula (ind)",
  "M4_d2: Nivel educ × Clima aula (ind)",
  "M4_e1: Libro × Participación voto (ind)",
  "M4_e2: Nivel educ × Participación voto (ind)",
  "M4_f1: Libro × Asamblea (ind)",
  "M4_f2: Nivel educ × Asamblea (ind)"
)

archivo_docx <- here::here("output", "Modelos_indice", "modelos_PACES_2019_indice_voto.doc")

tab_model(
  M0, M1, M1_a, M1_b, M2, M3_a, M3_b, M3_c,
  M4_a1, M4_b1, M4_a2, M4_b2, M4_c1, M4_c2,
  M4_d1, M4_d2, M4_e1, M4_e2, M4_f1, M4_f2,
  show.re.var = TRUE,
  show.icc    = TRUE,
  show.r2     = TRUE,
  show.ci     = FALSE,
  show.p      = FALSE,
  p.style     = "stars",
  dv.labels   = etiquetas,
  file        = archivo_docx
)
```

#### Test ANOVA

```{r}
anova_PACES_2019 <- dplyr::bind_rows(
  comparar_pendiente_aleatoria(M1, M1_a, "PACES_2019", "libro"),
  comparar_pendiente_aleatoria(M1, M1_b, "PACES_2019", "nivel_educ")
)
```


#### ANOVA final

```{r}
tabla_anova_pendientes <- dplyr::bind_rows(
  anova_CIVED_1999, anova_ICCS_2009, anova_ICCS_2016, anova_PACES_2019
)

exportar_tabla_efectos(
  tabla_anova_pendientes,
  here::here("output", "Modelos_indice", "anova_pendientes_aleatorias.docx")
)
```
 
